<?php
	$GLOBALS["ICON_FAMILY"]="PARAMETERS";
	include_once('ressources/class.templates.inc');
	include_once('ressources/class.ldap.inc');
	include_once('ressources/class.users.menus.inc');
	include_once('ressources/class.system.network.inc');
	include_once('ressources/class.os.system.inc');
	include_once('ressources/class.samba.inc');
	if(isset($_GET["verbose"])){$GLOBALS["VERBOSE"]=true;ini_set('html_errors',0);ini_set('display_errors', 1);ini_set('error_reporting', E_ALL);}
	
$usersmenus=new usersMenus();



if($user->AsSquidAdministrator==false){die('not allowed');}
if($user->CORP_LICENSE==false){die('License failed');}
if(isset($_GET["popup"])){popup();exit;}
if(isset($_POST["c-icap-error-page"])){SAVE();exit;}
js();


function js(){
	$page=CurrentPageName();
	$tpl=new templates();
	$title=$tpl->_ENGINE_parse_body("{alert_page}");
	$html="YahooWin6('650','$page?popup=yes','$title')";
	echo $html;
}

function popup(){
	$t=time();
	$default="<html>\n <head>\n <title>VIRUS FOUND</title>\n</head>\n\n<body>\n<h1>VIRUS FOUND</h1>\n\n\nYou tried to upload/download a file that contains the virus: \n   <b> %VVN </b>\n<br>\nThe Http location is: \n<b>  %huo </b>\n\n<p>\n  For more information contact your system administrator\n\n<hr>\n<p>\nThis message generated by C-ICAP service: <b> %iu </b>\n<br>Clamav antivirus engine: <b> %VVV </b>\n\n</p>\n\n</body>\n</html>";	
	$tpl=new templates();
	$page=CurrentPageName();
	$sock=new sockets();
	$CiCApErrorPage=base64_decode($sock->GET_INFO("CiCApErrorPage"));
	if($CiCApErrorPage==null){$CiCApErrorPage=$default;}
	
	$html="
	<i>Tokens:%VVN,%huo,%iu,%VVV</i>
	<textarea style='width:100%;height:450px;font-family:monospace;
	overflow:auto;font-size:13px;border:4px solid #CCCCCC;background-color:transparent' 
	id='c-icap-error-page'>$CiCApErrorPage</textarea>
	<div style='width:100%;text-align:right'><hr>". button("{apply}","SaveTemplateForm$t()",16)."</div>
	</div>
	<script>
	var x_SaveTemplateForm$t=function(obj){
		var results=obj.responseText;
		if(results.length>3){alert(results);}
		YahooWin6Hide();
    }	    
	
	 function SaveTemplateForm$t(){
      	var XHR = new XHRConnection();
      	XHR.appendData('c-icap-error-page',document.getElementById('c-icap-error-page').value);
      	XHR.sendAndLoad('$page', 'POST',x_SaveTemplateForm$t);          
      }	
     </script>	
	";	

	echo $tpl->_ENGINE_parse_body($html);
	
	
}

function SAVE(){
	$sock=new sockets();
	$DATA=base64_encode(stripslashes($_POST["c-icap-error-page"]));
	$sock->SaveConfigFile($DATA, "CiCApErrorPage");
	$sock->getFrameWork("squid.php?cicap-template=yes");
}

