<?php
include_once(dirname(__FILE__)."/framework/frame.class.inc");
include_once(dirname(__FILE__).'/framework/class.unix.inc');

debian_init();

function debian_init(){
$unix=new unix();

$updatercd=$unix->find_program("update-rc.d");
if(!is_file($updatercd)){
	echo "PLEASE WAIT.... update-rc.d no such binary: skip...\n";
	return;}

echo "PLEASE WAIT.... Creating startup samba scripts for SMBD and WINBINDD\n";
	
$f[]="#!/bin/sh";
$f[]="";
$f[]="### BEGIN INIT INFO";
$f[]="# Provides:          samba";
$f[]="# Required-Start:    \$network \$local_fs \$remote_fs";
$f[]="# Required-Stop:     \$network \$local_fs \$remote_fs";
$f[]="# Default-Start:     2 3 4 5";
$f[]="# Default-Stop:      0 1 6";
$f[]="# Should-Start:      slapd";
$f[]="# Should-Stop:       slapd";
$f[]="# Short-Description: start Samba daemons (nmbd and smbd)";
$f[]="### END INIT INFO";
$f[]="";
$f[]="";
$f[]="# Defaults";
$f[]="RUN_MODE=\"daemons\"";
$f[]="";
$f[]="# Reads config file (will override defaults above)";
$f[]="[ -r /etc/default/samba ] && . /etc/default/samba";
$f[]="";
$f[]="PIDDIR=/var/run/samba";
$f[]="NMBDPID=\$PIDDIR/nmbd.pid";
$f[]="SMBDPID=\$PIDDIR/smbd.pid";
$f[]="";
$f[]="# clear conflicting settings from the environment";
$f[]="unset TMPDIR";
$f[]="";
$f[]="# See if the daemons are there";
$f[]="test -x /usr/sbin/nmbd -a -x /usr/sbin/smbd || exit 0";
$f[]="";
$f[]=". /lib/lsb/init-functions";
$f[]="";
$f[]="case \"\$1\" in";
$f[]="	start)";
$f[]="		log_daemon_msg \"Starting Samba daemons\"";
$f[]="		# Make sure we have our PIDDIR, even if it's on a tmpfs";
$f[]="		install -o root -g root -m 755 -d \$PIDDIR";
$f[]="";
$f[]="		NMBD_DISABLED=`testparm -s --parameter-name='disable netbios' 2>/dev/null`";
$f[]="		if [ \"\$NMBD_DISABLED\" != 'Yes' ]; then";
$f[]="			log_progress_msg \"nmbd\"";
$f[]="			if ! start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/nmbd -- -D";
$f[]="			then";
$f[]="				log_end_msg 1";
$f[]="				exit 1";
$f[]="			fi";
$f[]="		fi";
$f[]="";
$f[]="		if [ \"\$RUN_MODE\" != \"inetd\" ]; then";
$f[]="			log_progress_msg \"smbd\"";
$f[]="			if ! start-stop-daemon --start --quiet --oknodo --exec /usr/sbin/smbd -- -D; then";
$f[]="				log_end_msg 1";
$f[]="				exit 1";
$f[]="			fi";
$f[]="		fi";
$f[]="";
$f[]="		log_end_msg 0";
$f[]="		;;";
$f[]="	stop)";
$f[]="		log_daemon_msg \"Stopping Samba daemons\"";
$f[]="		log_progress_msg \"nmbd\"";
$f[]="";
$f[]="		start-stop-daemon --stop --quiet --pidfile \$NMBDPID";
$f[]="		# Wait a little and remove stale PID file";
$f[]="		sleep 1";
$f[]="		if [ -f \$NMBDPID ] && ! ps h `cat \$NMBDPID` > /dev/null";
$f[]="		then";
$f[]="			# Stale PID file (nmbd was succesfully stopped),";
$f[]="			# remove it (should be removed by nmbd itself IMHO.)";
$f[]="			rm -f \$NMBDPID";
$f[]="		fi";
$f[]="";
$f[]="		if [ \"\$RUN_MODE\" != \"inetd\" ]; then";
$f[]="			log_progress_msg \"smbd\"";
$f[]="			start-stop-daemon --stop --quiet --pidfile \$SMBDPID";
$f[]="			# Wait a little and remove stale PID file";
$f[]="			sleep 1";
$f[]="			if [ -f \$SMBDPID ] && ! ps h `cat \$SMBDPID` > /dev/null";
$f[]="			then";
$f[]="				# Stale PID file (nmbd was succesfully stopped),";
$f[]="				# remove it (should be removed by smbd itself IMHO.)";
$f[]="				rm -f \$SMBDPID";
$f[]="			fi";
$f[]="		fi";
$f[]="";
$f[]="		log_end_msg 0";
$f[]="";
$f[]="		;;";
$f[]="	reload)";
$f[]="		log_daemon_msg \"Reloading /etc/samba/smb.conf\" \"smbd only\"";
$f[]="";
$f[]="		start-stop-daemon --stop --signal HUP --pidfile \$SMBDPID";
$f[]="";
$f[]="		log_end_msg 0";
$f[]="		;;";
$f[]="	restart|force-reload)";
$f[]="		\$0 stop";
$f[]="		sleep 1";
$f[]="		\$0 start";
$f[]="		;;";
$f[]="        status)";
$f[]="		status=\"0\"";
$f[]="		NMBD_DISABLED=`testparm -s --parameter-name='disable netbios' 2>/dev/null`";
$f[]="		if [ \"\$NMBD_DISABLED\" != \"Yes\" ]; then";
$f[]="			status_of_proc -p \$NMBDPID /usr/sbin/nmbd nmbd || status=\$?";
$f[]="		fi";
$f[]="		if [ \"\$RUN_MODE\" != \"inetd\" ]; then";
$f[]="			status_of_proc -p \$SMBDPID /usr/sbin/smbd smbd || status=\$?";
$f[]="		fi";
$f[]="		if [ \"\$NMBD_DISABLED\" = \"Yes\" -a \"\$RUN_MODE\" = \"inetd\" ]; then";
$f[]="			status=\"4\"";
$f[]="		fi";
$f[]="		exit \$status";
$f[]="		;;";
$f[]="	*)";
$f[]="		echo \"Usage: /etc/init.d/samba {start|stop|reload|restart|force-reload|status}\"";
$f[]="		exit 1";
$f[]="		;;";
$f[]="esac";
$f[]="";
$f[]="exit 0";
$f[]="";

@file_put_contents("/etc/init.d/samba", @implode("\n", $f));
@chmod("/etc/init.d/samba", 0755);
$f=array();
shell_exec("$updatercd -f samba defaults >/dev/null 2>&1");

$f[]="#!/bin/sh";
$f[]="";
$f[]="### BEGIN INIT INFO";
$f[]="# Provides:          winbind";
$f[]="# Required-Start:    \$network \$remote_fs \$syslog";
$f[]="# Required-Stop:     \$network \$remote_fs \$syslog";
$f[]="# Default-Start:     2 3 4 5";
$f[]="# Default-Stop:      0 1 6";
$f[]="# Short-Description: start Winbind daemon";
$f[]="### END INIT INFO";
$f[]="";
$f[]="";
$f[]="PATH=/sbin:/bin:/usr/sbin:/usr/bin";
$f[]="";
$f[]="[ -r /etc/default/winbind ] && . /etc/default/winbind";
$f[]="";
$f[]="DAEMON=/usr/sbin/winbindd";
$f[]="PIDDIR=/var/run/samba";
$f[]="WINBINDPID=\$PIDDIR/winbindd.pid";
$f[]="";
$f[]="# clear conflicting settings from the environment";
$f[]="unset TMPDIR";
$f[]="";
$f[]="# See if the daemon is there";
$f[]="test -x \$DAEMON || exit 0";
$f[]="";
$f[]=". /lib/lsb/init-functions";
$f[]="";
$f[]="case \"\$1\" in";
$f[]="	start)";
$f[]="		log_daemon_msg \"Starting the Winbind daemon\" \"winbind\"";
$f[]="";
$f[]="		mkdir -p /var/run/samba/winbindd_privileged || return 1";
$f[]="		chgrp winbindd_priv \$PIDDIR/winbindd_privileged/ || return 1";
$f[]="		chmod 0750 \$PIDDIR/winbindd_privileged/ || return 1";
$f[]="		start-stop-daemon --start --quiet --oknodo --exec \$DAEMON -- \$WINBINDD_OPTS";
$f[]="";
$f[]="		log_end_msg \$?";
$f[]="		;;";
$f[]="";
$f[]="	stop)";
$f[]="		log_daemon_msg \"Stopping the Winbind daemon\" \"winbind\"";
$f[]="		start-stop-daemon --stop --quiet --oknodo --exec \$DAEMON";
$f[]="		log_end_msg \$?";
$f[]="		;;";
$f[]="";
$f[]="	restart|force-reload)";
$f[]="		\$0 stop && sleep 2 && \$0 start";
$f[]="		;;";
$f[]="";
$f[]="	status)";
$f[]="		status_of_proc -p \$WINBINDPID \$DAEMON winbind && exit 0 || exit \$?";
$f[]="		;;";
$f[]="	*)";
$f[]="		echo \"Usage: /etc/init.d/winbind {start|stop|restart|force-reload|status}\"";
$f[]="		exit 1";
$f[]="		;;";
$f[]="esac";
$f[]="";
$f[]="exit 0";
$f[]="";
@file_put_contents("/etc/init.d/winbind", @implode("\n", $f));
@chmod("/etc/init.d/winbind", 0755);
$f=array();
shell_exec("$updatercd -f winbind defaults >/dev/null 2>&1");
echo "PLEASE WAIT.... Creating startup samba scripts for SMBD and WINBINDD DONE !\n";	
}