<?php

class array_category_school{
	
	
	function return_array($cleanedkey=false){
		
		$MAIN["liu.se"]=True;
		$MAIN["su.se"]=True;
		$MAIN["umanitoba.ca"]=True;
		$MAIN["ucalgary.ca"]=True;
		$MAIN["kth.se"]=True;
		$MAIN["educacion.gob.ar"]=True;
		
		$MAIN["dal.ca"]=True;
		$MAIN["vutbr.cz"]=True;
		$MAIN["bme.hu"]=True;
		$MAIN["usp.br"]=True;
		$MAIN["lu.se"]=True;
		$MAIN["unam.mx"]=True;
		$MAIN["onsnetstudenten.nl"]=True;
		$MAIN["fu-berlin.de"]=True;
		$MAIN["tue.nl"]=True;
		$MAIN["uwaterloo.ca"]=True;
		$MAIN["ualberta.ca"]=True;
		
		$MAIN["school.nz"]=True;
		$MAIN["k12.tr"]=True;
		$MAIN["k12.ca.us"]=True;
		$MAIN["k12.sd.us"]=True;
		$MAIN["school.nz"]=True;
		$MAIN["schoolloop.com"]=True;
		$MAIN["50school.com"]=True;
		$MAIN["sch.id"]=True;
		$MAIN["uchicago.edu"]=True;
		$MAIN["univ-paris1.fr"]=True;
		$MAIN["ac-versailles.fr"]=True;
		$MAIN["harvard.edu"]=True;
		$MAIN["sa.edu.au"]=True;
		$MAIN["oh.us"]=True;
		$MAIN["vic.edu.au"]=True;
		$MAIN["sujet-philo.com"]=True;
		$MAIN["utoronto.ca"]=True;
		$MAIN["olemiss.edu"]=True;
		$MAIN["uwo.ca"]=True;
		$MAIN["glogster.com"]=True;
		$MAIN["mit.edu"]=True;
		$MAIN["uwc.ac.za"]=True;
		$MAIN["buffalo.edu"]=True;
		$MAIN["uj.ac.za"]=True;
		$MAIN["dundee.ac.uk"]=True;
		$MAIN["unesp.br"]=True;
		$MAIN["ied.edu.hk"]=True;
		$MAIN["leidenuniv.nl"]=True;
		$MAIN["tohoku.ac.jp"]=True;
		$MAIN["uni-erlangen.de"]=True;
		$MAIN["hstc.edu.cn"]=True;
		$MAIN["uz.ac.zw"]=True;
		$MAIN["kaist.ac.kr"]=True;
		$MAIN["utexas.edu"]=True;
		$MAIN["univ-rennes1.fr"]=True;
		$MAIN["okstate.edu"]=True;
		$MAIN["nmt.edu"]=True;
		$MAIN["okstate.edu"]=True;
		$MAIN["sun.ac.za"]=True;
		$MAIN["uni-marburg.de"]=True;
		
		
		
		$MAIN["uky.edu"]=True;
		$MAIN["virtual-college.co.uk"]=True;
		$MAIN["oneonta.edu"]=True;
		
		$MAIN["archives-ouvertes.fr"]=True;
		$MAIN["nsw.edu.au"]=True;
		$MAIN["stanford.edu"]=True;
		$MAIN["u-bordeaux.fr"]=True;
		$MAIN["upenn.edu"]=True;
		$MAIN["wau.nl"]=True;
		$MAIN["lyceesaintambroise.local"]=True;
		$MAIN["vc-graz.ac.at"]=True;
		$MAIN["catholic.edu.au"]=True;
		$MAIN["rug.nl"]=True;
		$MAIN["rit.edu"]=True;
		$MAIN["unc.edu"]=True;
		$MAIN["ncsu.edu"]=True;
		$MAIN["ntnu.no"]=True;
		$MAIN["ust.hk"]=True;
		$MAIN["unam.mx"]=True;
		$MAIN["utwente.nl"]=True;
		$MAIN["ucla.edu"]=True;
		$MAIN["umd.edu"]=True;
		$MAIN["vt.edu"]=True;
		$MAIN["cmu.edu"]=True;
		
		$MAIN["berkeley.edu"]=True;
		$MAIN["cvut.cz"]=True;
		$MAIN["purdue.edu"]=True;
		$MAIN["uu.se"]=True;
		$MAIN["ed.ac.uk"]=True;
		$MAIN["cam.ac.uk"]=True;
		$MAIN["ucsc.edu"]=True;
		$MAIN["tu-darmstadt.de"]=True;
		$MAIN["uni-leipzig.de"]=True;
		$MAIN["tu-dresden.de"]=True;
		$MAIN["uni-ulm.de"]=True;
		$MAIN["unl.edu"]=True;
		$MAIN["ethz.ch"]=True;
		$MAIN["edublogs.org"]=True;
		$MAIN["umich.edu"]=True;
		$MAIN["uni-frankfurt.de"]=True;
		$MAIN["nctu.edu.tw"]=True;
		$MAIN["nyu.edu"]=True;
		$MAIN["utk.edu"]=True;
		$MAIN["iastate.edu"]=True;
		$MAIN["queensu.ca"]=True;
		$MAIN["syr.edu"]=True;
		$MAIN["yale.edu"]=True;
		$MAIN["usc.edu"]=True;
		$MAIN["uio.no"]=True;
		$MAIN["ucsf.edu"]=True;
		$MAIN["uni-konstanz.de"]=True;
		$MAIN["ucsd.edu"]=True;
		$MAIN["umu.se"]=True;
		$MAIN["ox.ac.uk"]=True;
		$MAIN["tu-clausthal.de"]=True;
		$MAIN["uci.edu"]=True;		
		$MAIN["uni-paderborn.de"]=True;
		$MAIN["polimi.it"]=True;
		$MAIN["mcgill.ca"]=True;
		$MAIN["uoguelph.ca"]=True;
		$MAIN["wroc.pl"]=True;
		$MAIN["ucm.es"]=True;
		$MAIN["uva.nl"]=True;
		$MAIN["uga.edu"]=True;
		$MAIN["unipi.it"]=True;
		$MAIN["uniroma1.it"]=True;
		$MAIN["tamu.edu"]=True;
		
		$MAIN["univ-lyon1.fr"]=True;
		$MAIN["uoregon.edu"]=True;
		$MAIN["ucc.ie"]=True;
		$MAIN["ac-rouen.fr"]=True;
		
		$MAIN["cademia.edu"]=True;
		$MAIN["uni-linz.ac.at"]=True;
		$MAIN["uark.edu"]=True;
		$MAIN["elte.hu"]=True;
		$MAIN["drexel.edu"]=True;
		$MAIN["ufl.edu"]=True;
		$MAIN["sunysb.edu"]=True;
		$MAIN["qld.edu.au"]=True;
		$MAIN["uchile.cl"]=True;
		$MAIN["hj.se"]=True;
		$MAIN["tudelft.nl"]=True;
		$MAIN["udel.edu"]=True;
		$MAIN["ac-aix-marseille.fr"]=True;
		$MAIN["cityu.edu.hk"]=True;
		$MAIN["oregonstate.edu"]=True;
		$MAIN["duke.edu"]=True;
		$MAIN["illinois.edu"]=True;
		$MAIN["memphis.edu"]=True;
		$MAIN["nmsu.edu"]=True;
		$MAIN["uni-goettingen.de"]=True;
		$MAIN["tsinghua.edu.cn"]=True;
		$MAIN["hawaii.edu"]=True;
		$MAIN["epfl.ch"]=True;
		$MAIN["cuni.cz"]=True;
		$MAIN["utah.edu"]=True;
		$MAIN["uta.edu"]=True;
		$MAIN["uni-bayreuth.de"]=True;
		$MAIN["uni-hamburg.de"]=True;
		$MAIN["virginia.edu"]=True;
		$MAIN["uni-mainz.de"]=True;
		$MAIN["upol.cz"]=True;
		$MAIN["ac-creteil.fr"]=True;
		$MAIN["chalmers.se"]=True;
		$MAIN["ac-orleans-tours.fr"]=True;
		$MAIN["k12.wi.us"]=True;
		$MAIN["ufsc.br"]=True;
		$MAIN["unimib.it"]=True;
		$MAIN["univ-lille1.fr"]=True;
		$MAIN["studyisland.com"]=True;
		$MAIN["usf.edu"]=True;
		$MAIN["bu.edu"]=True;
		$MAIN["wsu.edu"]=True;
		$MAIN["maine.edu"]=True;
		$MAIN["columbia.edu"]=True;
		$MAIN["ntu.edu.tw"]=True;
		$MAIN["nthu.edu.tw"]=True;
		$MAIN["umn.edu"]=True;
		$MAIN["cornell.edu"]=True;
		$MAIN["psu.edu"]=True;
		$MAIN["ucdavis.edu"]=True;
		$MAIN["northwestern.edu"]=True;
		$MAIN["wa.edu.au"]=True;
		$MAIN["princeton.edu"]=True;
		$MAIN["fiu.edu"]=True;
		$MAIN["wisc.edu"]=True;
		$MAIN["uconn.edu"]=True;
		$MAIN["rutgers.edu"]=True;
		$MAIN["cwru.edu"]=True;
		$MAIN["nmu.edu"]=True;
		$MAIN["uic.edu"]=True;
		$MAIN["msu.edu"]=True;
		$MAIN["ksu.edu"]=True;
		$MAIN["mtu.edu"]=True;
		$MAIN["cuhk.edu.hk"]=True;
		$MAIN["brown.edu"]=True;
		$MAIN["edu.jo"]=True;
		$MAIN["act.edu.au"]=True;
		$MAIN["wustl.edu"]=True;
		$MAIN["tufts.edu"]=True;
		$MAIN["wpi.edu"]=True;
		$MAIN["umass.edu"]=True;
		$MAIN["nau.edu"]=True;
		$MAIN["ucr.edu"]=True;
		$MAIN["gsu.edu"]=True;
		$MAIN["um.edu.my"]=True;
		$MAIN["unsw.edu.au"]=True;
		$MAIN["nsysu.edu.tw"]=True;
		$MAIN["nodak.edu"]=True;
		$MAIN["ohio-state.edu"]=True;
		$MAIN["ccu.edu.tw"]=True;
		$MAIN["metu.edu.tr"]=True;
		$MAIN["tp.edu.tw"]=True;
		$MAIN["uwm.edu"]=True;
		
		$MAIN["washington.edu"]=True;
		$MAIN["uiowa.edu"]=True;
		$MAIN["smu.edu"]=True;
		$MAIN["academia.edu"]=True;
		$MAIN["osu.edu"]=True;
		$MAIN["asu.edu"]=True;
		$MAIN["unimelb.edu.au"]=True;
		$MAIN["depaul.edu"]=True;
		$MAIN["arizona.edu"]=True;
		$MAIN["dartmouth.edu"]=True;
		$MAIN["albany.edu"]=True;
		$MAIN["fju.edu.tw"]=True;
		$MAIN["nus.edu.sg"]=True;
		$MAIN["anu.edu.au"]=True;
		$MAIN["auburn.edu"]=True;
		$MAIN["iup.edu"]=True;
		$MAIN["ua.edu"]=True;
		$MAIN["pitt.edu"]=True;
		$MAIN["emory.edu"]=True;
		$MAIN["indiana.edu"]=True;
		$MAIN["fsu.edu"]=True;
		
		$MAIN["ucsb.edu"]=True;
		$MAIN["fhsu.edu"]=True;
		$MAIN["gatech.edu"]=True;
		$MAIN["ncu.edu.tw"]=True;
		$MAIN["cuny.edu"]=True;
		$MAIN["kent.edu"]=True;
		$MAIN["unlp.edu.ar"]=True;
		$MAIN["mtholyoke.edu"]=True;
		$MAIN["brynmawr.edu"]=True;
		$MAIN["uiuc.edu"]=True;
		$MAIN["mst.edu"]=True;
		$MAIN["uni-freiburg.de"]=True;
		$MAIN["u-strasbg.fr"]=True;
		$MAIN["ac-reunion.fr"]=True;
		$MAIN["u-paris10.fr"]=True;
		$MAIN["u-psud.fr"]=True;
		$MAIN["univ-nantes.fr"]=True;
		$MAIN["ac-nantes.fr"]=True;
		
		$MAIN["uni-rostock.de"]=True;
		$MAIN["uni-heidelberg.de"]=True;
		$MAIN["uni-regensburg.de"]=True;
		$MAIN["uni-bremen.de"]=True;
		$MAIN["uni-kl.de"]=True;
		$MAIN["uni-muenster.de"]=True;
		$MAIN["ruhr-uni-bochum.de"]=True;
		$MAIN["uni-mb.si"]=True;
		$MAIN["uni-oldenburg.de"]=True;
		$MAIN["uni-muenchen.de"]=True;
		$MAIN["uni-weimar.de"]=True;
		$MAIN["uni-lj.si"]=True;
		$MAIN["uni-duesseldorf.de"]=True;
		
		$MAIN["univie.ac.at"]=True;
		$MAIN["ucl.ac.be"]=True;
		$MAIN["tu-graz.ac.at"]=True;
		$MAIN["ulb.ac.be"]=True;
		$MAIN["ulg.ac.be"]=True;
		$MAIN["hokudai.ac.jp"]=True;
		
	
		
		
		
		
		$array=array("universidad-finis-terrae","finisterrae.cl","tu-harburg","mathletics","grenet","powerschool",
				"schoology","edublogs","sumdog","tableau-noir","avcr.cz","revues.org","uni-tuebingen.de","reseauecoleetnature.org","educationamerica","stv-chaville.com","hbxxedu.com","uam.es","u-cergy","espace-eleves.com");
		
		
		
		while (list ($www, $cat) = each ($MAIN) ){
			$array[]=$www;
				
		}
		
		
		if(!$cleanedkey){return $array;}
		while (list ($index, $www) = each ($array) ){
			if(strpos(" $www", ".")==0){continue;}
			if(strpos(" $www", "*")>0){continue;}
			$XRETURN[$www]=true;
		}
		
		return $XRETURN;
	}
	
	
}
