<?php

class array_category_governments{
	
	
	
	function return_array($cleanedkey=false){
		$MAIN["gov.bc.ca"]=true;
		$MAIN["gouv.qc.ca"]=true;
		$MAIN["gouv.sn"]=true;
		$MAIN["gov.la"]=true;
		$MAIN["gov.co"]=true;
		$MAIN["gov.ng"]=true;
		$MAIN["gov.cn"]=true;
		$MAIN["gov.uk"]=true;
		$MAIN["gov.co"]=true;
		$MAIN["gov.in"]=true;
		$MAIN["gov.tr"]=true;
		$MAIN["gov.ru"]=true;
		
		$MAIN["gob.mx"]=true;
		$MAIN["gov.bm"]=true;
		$MAIN["gov.bw"]=true;
		$MAIN["gov.cn"]=true;
		$MAIN["gov.gg"]=true;
		$MAIN["gov.hk"]=true;
		$MAIN["gov.il"]=true;
		$MAIN["gov.im"]=true;
		$MAIN["gov.kg"]=true;
		$MAIN["gov.ky"]=true;
		$MAIN["gov.lk"]=true;
		$MAIN["gov.me"]=true;
		$MAIN["gov.mo"]=true;
		$MAIN["gov.mt"]=true;
		$MAIN["gov.ph"]=true;
		$MAIN["gov.ru"]=true;
		$MAIN["gov.sg"]=true;
		$MAIN["gov.tw"]=true;
		$MAIN["gov.uz"]=true;
		$MAIN["gov.vn"]=true;
		$MAIN["gov.za"]=true;
		$MAIN["gov.br"]=true;
		$MAIN["gov.au"]=true;
		$MAIN["gov.ar"]=true;
		$MAIN["gov.ve"]=true;
		$MAIN["gov.it"]=true;
		$MAIN["gov.pt"]=true;
		$MAIN["gov.ma"]=true;
		$MAIN["gov.ua"]=true;
		$MAIN["gov.gr"]=true;
		$MAIN["gov.hu"]=true;
		$MAIN["gov.my"]=true;
		$MAIN["gov.rw"]=true;
		$MAIN["gov.pg"]=true;
		$MAIN["gov.ir"]=true;
		$MAIN["gov.cl"]=true;
		$MAIN["gov.kz"]=true;
		$MAIN["gov.tn"]=true;
		$MAIN["gov.pk"]=true;
		$MAIN["gouv.fr"]=true;
		$MAIN["gov.pl"]=true;
		$MAIN["gov.pf"]=true;
		$MAIN["gov.gh"]=true;
		$MAIN["gov.cv"]=true;
		$MAIN["gov.mn"]=true;
		$MAIN["gov.ml"]=true;
		$MAIN["gov.ba"]=true;
		$MAIN["gov.eg"]=true;
		$MAIN["gov.art"]=true;
		$MAIN["gov.si"]=true;
		$MAIN["gov.rs"]=true;
		$MAIN["gov.lb"]=true;
		$MAIN["gov.mm"]=true;
		$MAIN["gov.ii"]=true;
		$MAIN["gov.sk"]=true;
		$MAIN["gov.bf"]=true;
		$MAIN["gov.mb.ca"]=true;
		$MAIN["gov.zw"]=true;
		$MAIN["gov.sa"]=true;
		$MAIN["gov.cy"]=true;
		$MAIN["gov.py"]=true;
		$MAIN["gov.jm"]=true;
		$MAIN["gov.af"]=true;
		$MAIN["gov.jo"]=true;
		$MAIN["gov.cu"]=true;
		$MAIN["gov.sb"]=true;
		$MAIN["gov.mg"]=true;
		$MAIN["gov.by"]=true;
		$MAIN["gov.ec"]=true;
		$MAIN["gov.bi"]=true;
		$MAIN["gov.ae"]=true;
		$MAIN["gov.ps"]=true;
		$MAIN["gov.ro"]=true;
		$MAIN["gov.na"]=true;
		$MAIN["gov.kh"]=true;
		$MAIN["gov.sk.ca"]=true;
		$MAIN["gov.nt.ca"]=true;
		$MAIN["gov.do"]=true;
		$MAIN["gov.mr"]=true;
		$MAIN["gov.vg"]=true;
		$MAIN["gov.sc"]=true;
		$MAIN["gov.ab.ca"]=true;
		$MAIN["gov.co.com"]=true;
		$MAIN["gov.ie"]=true;
		$MAIN["gov.md"]=true;
		$MAIN["gov.on.ca"]=true;
		$MAIN["gov.cz"]=true;
		$MAIN["gov.qa"]=true;
		$MAIN["gov.tt"]=true;
		$MAIN["gov.et"]=true;
		$MAIN["gov.bt"]=true;
		$MAIN["gov.om"]=true;
		$MAIN["gov.bd"]=true;
		$MAIN["gov.dz"]=true;
		$MAIN["gov.bo"]=true;
		$MAIN["gov.ca"]=true;
		$MAIN["gov.fj"]=true;
		$MAIN["ca.gov.com"]=true;
		$MAIN["gov.sy"]=true;
		$MAIN["gov.bh"]=true;
		$MAIN["gov.vu"]=true;
		$MAIN["gov.nu.ca"]=true;
		$MAIN["gov.az"]=true;
		$MAIN["gov.vo"]=true;
		$MAIN["gov.gn"]=true;
		$MAIN["gov.ly"]=true;
		$MAIN["gov.je"]=true;
		$MAIN["gov.mk"]=true;
		$MAIN["gov.mv"]=true;
		$MAIN["gov.mu"]=true;
		$MAIN["gov.np"]=true;
		$MAIN["gov.al"]=true;
		$MAIN["gob.ar"]=true;
		$MAIN["gov.com.my"]=true;
		$MAIN["gov.spb.ru"]=true;
		$MAIN["gov.lv"]=true;
		$MAIN["gov.ge"]=true;
		$MAIN["gov.kw"]=true;
		$MAIN["gov.ye"]=true;
		$MAIN["gov.sd"]=true;
		$MAIN["gov.bn"]=true;
		$MAIN["gov.vc"]=true;
		$MAIN["gov.se"]=true;
		$MAIN["gov.iq"]=true;
		$MAIN["gouv.ga"]=true;
		$MAIN["gouv.mc"]=true;
		$MAIN["gouv.ml"]=true;
		$MAIN["gouv.com"]=true;
		$MAIN["gouv.ma"]=true;
		$MAIN["gouv.cd"]=true;
		$MAIN["gouv.ua"]=true;
		$MAIN["gouv.nc"]=true;
		$MAIN["gouv.ci"]=true;
		$MAIN["gouv.ht"]=true;
		$MAIN["gob.pe"]=true;
		$MAIN["gob.ve"]=true;
		$MAIN["gob.es"]=true;
		$MAIN["gob.bo"]=true;
		$MAIN["gob.cl"]=true;
		$MAIN["gob.ec"]=true;
		$MAIN["gob.ni"]=true;
		$MAIN["gob.gt"]=true;
		$MAIN["gob.sv"]=true;
		$MAIN["gob.do"]=true;
		$MAIN["gob.hn"]=true;
		$MAIN["cci.fr"]=true;
		$MAIN["ca.gov"]=true;
		
		$array=array("st-christo","cnam.fr","msh-vdl.fr","gov.uk","gov.yk.ca",
				"oecdilibrary.org","oecd.org","rhonealpes.fr","ineris.fr");
		
		while (list ($www, $cat) = each ($MAIN) ){
			$array[]=$www;
				
		}
		

		if(!$cleanedkey){return $array;}
		while (list ($index, $www) = each ($array) ){
			if(strpos(" $www", ".")==0){continue;}
			if(strpos(" $www", "*")>0){continue;}
			$XRETURN[$www]=true;
		}
		
		return $XRETURN;
	}
	
	
}
