<?php

class array_category_sciencecomputing{
	
	
	
	function return_array($cleanedkey=false){
		

		
		
		$array=array("artica.fr","canonical","n1adsl","astaro.com","internetarchaeology","herokuapp.com","agate-sigb.com","newegg.com","neweggimages.com.cn",
		"googlecode.com","proxyplus","novadata","apple.com","ipv6test.net","teknaria.com",
		"sourceforge.net","sagepub.com","capgemini","icsor.com","your-server.de",
		"opendns","planet-service.fr","sugarcrm.com","stackexchange.com",
		"symantec","ipv6test.semnicneposilejte.cz","groupe-sigma.com","mailinblack.com",
		"nabble","coremetrics.com","autodesk.com","accortech.com",
		"htp","atos.net","atosorigin","atosworldline","ipv6test.net",
		"citrix","dell","herculepro","archivospc.com","ricoh",
		"hyves","spiceworks","dslreports","itpub.net","redsoft.at","smtproutes.com",
		"sanasecurity","github","cmsmedia.fr","ora-code.com","netcode","global-coding.com",
		"canonical.com","dell","codes-sources","ibm","parallels","unveiltech","jquery","opera","windows\.microsoft","canon-europe","canon",
		"ubuntu","eye.fi","messagelabs.com","artica.fr","googlecode.com","omniroot","ie.microsoft.com","microsoft.com","dashnxdomain.net","dotnxdomain.net");
		$MAIN["domaintools.com"]=true;
		$MAIN["ccog.komputervpole.ru"]=true;
		$MAIN["webspeed.dk"]=true;
		$MAIN["ipv6test.semnicneposilejte.cz"]=true;
		$MAIN["corp.jos.com"]=true;
		$MAIN["phobos.apple.com"]=true;
		$MAIN["coco.com.de"]=true;
		$MAIN["swi.tune-up.com"]=true;
		$MAIN["komputervpole.ru"]=true;
		$MAIN["informer.com"]=true;
		$MAIN["sese.com.de"]=true;
		$MAIN["26uuu.com.de"]=true;
		$MAIN["telstra.net"]=true;
		$MAIN["qwe.com.de"]=true;
		$MAIN["24ddd.com.de"]=true;
		$MAIN["codeplex.com"]=true;
		$MAIN["msddn.com"]=true;
		$MAIN["flspp.com"]=true;
		$MAIN["oneall.com"]=true;
		$MAIN["foto.ua"]=true;
		$MAIN["1c-bitrix-cdn.ru"]=true;
		$MAIN["coveritlive.com"]=true;
		$MAIN["greencompute.org"]=true;
		$MAIN["github.com"]=true;
		$MAIN["developpez.com"]=true;
		$MAIN["hp.com"]=true;
		$MAIN["zendesk.com"]=true;
		$MAIN["opendns.com"]=true;
		$MAIN["windows.net"]=true;
		$MAIN["nabble.com"]=True;
		$MAIN["netzathleten-media.de"]=True;
		$MAIN["dedicatedornot.com"]=True;
		$MAIN["luckyorange.com"]=True;
		$MAIN["4r44.com"]=True;
		$MAIN["taleo.net"]=True;
		$MAIN["km.ua"]=True;
		$MAIN["unet.com"]=True;
		$MAIN["foroactivo.com"]=True;
		$MAIN["xaclip.com"]=True;
		$MAIN["mimecast.com"]=True;
		$MAIN["softonic.com"]=True;
		$MAIN["narkive.com"]=True;
		$MAIN["ripe.net"]=True;
		$MAIN["maxim.net"]=True;
		$MAIN["sumy.ua"]=True;
		$MAIN["technoportal.ua"]=True;
		$MAIN["stratoserver.net"]=True;
		$MAIN["mozilla.com"]=True;
		$MAIN["symantec.com"]=True;
		$MAIN["testflightapp.com"]=True;
		$MAIN["archive.org"]=True;
		$MAIN["inext.cz"]=True;
		$MAIN["cisco.com"]=True;
		$MAIN["live.com"]=True;
		$MAIN["oracle.com"]=True;
		$MAIN["aclst.com"]=True;
		$MAIN["wbs.cz"]=True;
		$MAIN["web.id"]=True;
		$MAIN["att.com"]=True;
		$MAIN["ks.ua"]=True;
		$MAIN["ovh.org"]=True;
		$MAIN["hupont.hu"]=True;
		$MAIN["kimsufi.com"]=True;
		$MAIN["streamon.fm"]=True;
		$MAIN["worldssl.net"]=True;
		$MAIN["softwaysolutions.com"]=True;
		$MAIN["peerius.com"]=True;
		$MAIN["akamaihd.net"]=True;
		$MAIN["sinaapp.com"]=True;
		$MAIN["prodomaines.com"]=True;
		$MAIN["appsitehosting.com"]=True;
		$MAIN["ctinets.com"]=True;
		
		$MAIN["online.de"]=True;
		$MAIN["dell.com"]=True;
		$MAIN["pphosted.com"]=True;
		$MAIN["github.io"]=true;
		$MAIN["gathering.org"]=true;
		$MAIN["gfcpl.com"]=true;
		$MAIN["msecn.net"]=true;
		$MAIN["3d330.com"]=true;
		$MAIN["uid.me"]=true;
		$MAIN["mopera.net"]=true;
		$MAIN["salesforceliveagent.com"]=true;
		
		
		$MAIN["apnic.net"]=True;
		$MAIN["msecndsl.net"]=True;
		$MAIN["dothome.co.kr"]=True;
		$MAIN["lg.ua"]=True;
		$MAIN["wpengine.com"]=True;
		$MAIN["uservoice.com"]=True;
		$MAIN["sakura.ne.jp"]=True;
		$MAIN["trendmicro.com"]=True;
		$MAIN["360.cn"]=True;
		$MAIN["adobe.com"]=True;
		$MAIN["araxinfo.com"]=True;
		$MAIN["msecnd.net"]=True;
		$MAIN["rv.ua"]=True;
		$MAIN["lithium.com"]=True;
		$MAIN["ibm.com"]=True;
		$MAIN["imsbiz.com"]=True;
		$MAIN["plus.com"]=True;
		$MAIN["apache.org"]=True;
		$MAIN["zol.com.cn"]=True;
		$MAIN["webgarden.cz"]=True;
		
		$MAIN["adobeconnect.com"]=True;
		$MAIN["oneminutesite.it"]=True;
		$MAIN["asus.com"]=True;
		$MAIN["mcafee.com"]=True;
		$MAIN["as41690.net"]=True;
		$MAIN["opera.com"]=True;
		$MAIN["rmt.ru"]=True;
		$MAIN["rssing.com"]=True;
		$MAIN["tagcommander.com"]=True;
		$MAIN["data-hotel.net"]=True;
		
		$MAIN["siteapps.com"]=True;
		
		$MAIN["php.net"]=True;
		$MAIN["hotwords.com.br"]=True;
		$MAIN["ipaddress.com"]=True;
		$MAIN["wapka.mobi"]=True;
		$MAIN["appriver.com"]=True;
		$MAIN["netguestbook.com"]=True;
		$MAIN["multiguestbook.com"]=True;
		$MAIN["clubic.com"]=True;
		$MAIN["eset.com"]=True;
		$MAIN["intel.com"]=True;
		
		
		
		while (list ($www, $cat) = each ($MAIN) ){
			$array[]=$www;
				
		}
		
		
		if(!$cleanedkey){return $array;}
		while (list ($index, $www) = each ($array) ){
			if(strpos(" $www", ".")==0){continue;}
			if(strpos(" $www", "*")>0){continue;}
			$XRETURN[$www]=true;
		}
		
		return $XRETURN;
	}
	
	
}
